### ISSUE TITLE
Add our design token to tailwind config

### ISSUE THREAD

**Issue by tanerijun** [Hack-Weekly/lavender-snake-blog#18]
Using css variable might be a good idea. It makes theming way easier, we don't need to use `dark:` from tailwind anymore

**Comment by Xarunoba** [comment]
# Tailwind Theme
Status: `WIP`
Created `tailwind-theme` branch to work on the theme.

I had to do some edits to the primary palette based on the Design System Figma in order to make it with the 50-950 shades system of Tailwind CSS. I used this tool: https://palettte.app/

## Check List

- [x] Primary Colors
- [ ] Secondary Colors
- [ ] Neutral Colors
- [ ] Success Colors
- [ ] Error Colors
- [x] Font Family
- [ ] Font Sizes

## Primary Colors
```
#060011
#11062B
#1E0D45
#2D165B
#3E256F
#4F378B
#674D9B
#816EB3
#A692D1
#C8BBEA
#F0EBFF
```

## Secondary Colors
```
TODO: Secondary Colors
```

## Neutral Colors
```
TODO: Neutral Colors
```

## Success Colors
```
TODO: Success Colors
```

## Error Colors
```
TODO: Error Colors
```

## Font Family
```
Archivo, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'
```

## Font Sizes
```
TODO: Font Sizes
```

**Comment by tanerijun** [comment]
Ignore the CSS variables stuffs I said up there. Let's do it the Tailwind way. I'll make the `ThemeToggler` component add `class="dark"` to root html on toggle
